appname = eventos_crud
runmode = ${EVENTOS_CRUD_RUN_MODE||prod}
httpport = ${EVENTOS_CRUD_HTTP_PORT}
autorender = false
copyrequestbody = true

parameterStore = ${PARAMETER_STORE}
PGuser=${EVENTOS_CRUD_PGUSER}
PGpass=${EVENTOS_CRUD_PGPASS}
PGhost=${EVENTOS_CRUD_PGHOST}
PGport=${EVENTOS_CRUD_PGPORT}
PGdb=${EVENTOS_CRUD_PGDB}
PGschema=${EVENTOS_CRUD_PGSCHEMA}
